// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated from: data/exercises/generate_localization_helper.dart

import 'package:workin_fit/l10n/app_localizations.dart';

/// Helper class to get localized exercise strings
class ExerciseLocalizationHelper {
  /// Get localized string by key
  static String? getString(AppLocalizations localizations, String key) {
    switch (key) {
      case 'exercise_cardio_001_name':
        return localizations.exercise_cardio_001_name;
      case 'exercise_cardio_001_description':
        return localizations.exercise_cardio_001_description;
      case 'exercise_cardio_001_beginner_tips':
        return localizations.exercise_cardio_001_beginner_tips;
      case 'exercise_cardio_002_name':
        return localizations.exercise_cardio_002_name;
      case 'exercise_cardio_002_description':
        return localizations.exercise_cardio_002_description;
      case 'exercise_cardio_002_beginner_tips':
        return localizations.exercise_cardio_002_beginner_tips;
      case 'exercise_cardio_003_name':
        return localizations.exercise_cardio_003_name;
      case 'exercise_cardio_003_description':
        return localizations.exercise_cardio_003_description;
      case 'exercise_cardio_003_beginner_tips':
        return localizations.exercise_cardio_003_beginner_tips;
      case 'exercise_cardio_004_name':
        return localizations.exercise_cardio_004_name;
      case 'exercise_cardio_004_description':
        return localizations.exercise_cardio_004_description;
      case 'exercise_cardio_004_beginner_tips':
        return localizations.exercise_cardio_004_beginner_tips;
      case 'exercise_cardio_005_name':
        return localizations.exercise_cardio_005_name;
      case 'exercise_cardio_005_description':
        return localizations.exercise_cardio_005_description;
      case 'exercise_cardio_005_beginner_tips':
        return localizations.exercise_cardio_005_beginner_tips;
      case 'exercise_cardio_006_name':
        return localizations.exercise_cardio_006_name;
      case 'exercise_cardio_006_description':
        return localizations.exercise_cardio_006_description;
      case 'exercise_cardio_006_beginner_tips':
        return localizations.exercise_cardio_006_beginner_tips;
      case 'exercise_cardio_007_name':
        return localizations.exercise_cardio_007_name;
      case 'exercise_cardio_007_description':
        return localizations.exercise_cardio_007_description;
      case 'exercise_cardio_007_beginner_tips':
        return localizations.exercise_cardio_007_beginner_tips;
      case 'exercise_cardio_008_name':
        return localizations.exercise_cardio_008_name;
      case 'exercise_cardio_008_description':
        return localizations.exercise_cardio_008_description;
      case 'exercise_cardio_008_beginner_tips':
        return localizations.exercise_cardio_008_beginner_tips;
      case 'exercise_cardio_009_name':
        return localizations.exercise_cardio_009_name;
      case 'exercise_cardio_009_description':
        return localizations.exercise_cardio_009_description;
      case 'exercise_cardio_009_beginner_tips':
        return localizations.exercise_cardio_009_beginner_tips;
      case 'exercise_cardio_010_name':
        return localizations.exercise_cardio_010_name;
      case 'exercise_cardio_010_description':
        return localizations.exercise_cardio_010_description;
      case 'exercise_cardio_010_beginner_tips':
        return localizations.exercise_cardio_010_beginner_tips;
      case 'exercise_cardio_011_name':
        return localizations.exercise_cardio_011_name;
      case 'exercise_cardio_011_description':
        return localizations.exercise_cardio_011_description;
      case 'exercise_cardio_011_beginner_tips':
        return localizations.exercise_cardio_011_beginner_tips;
      case 'exercise_cardio_012_name':
        return localizations.exercise_cardio_012_name;
      case 'exercise_cardio_012_description':
        return localizations.exercise_cardio_012_description;
      case 'exercise_cardio_012_beginner_tips':
        return localizations.exercise_cardio_012_beginner_tips;
      case 'exercise_cardio_013_name':
        return localizations.exercise_cardio_013_name;
      case 'exercise_cardio_013_description':
        return localizations.exercise_cardio_013_description;
      case 'exercise_cardio_013_beginner_tips':
        return localizations.exercise_cardio_013_beginner_tips;
      case 'exercise_cardio_014_name':
        return localizations.exercise_cardio_014_name;
      case 'exercise_cardio_014_description':
        return localizations.exercise_cardio_014_description;
      case 'exercise_cardio_014_beginner_tips':
        return localizations.exercise_cardio_014_beginner_tips;
      case 'exercise_cardio_015_name':
        return localizations.exercise_cardio_015_name;
      case 'exercise_cardio_015_description':
        return localizations.exercise_cardio_015_description;
      case 'exercise_cardio_015_beginner_tips':
        return localizations.exercise_cardio_015_beginner_tips;
      case 'exercise_core_001_name':
        return localizations.exercise_core_001_name;
      case 'exercise_core_001_description':
        return localizations.exercise_core_001_description;
      case 'exercise_core_001_beginner_tips':
        return localizations.exercise_core_001_beginner_tips;
      case 'exercise_core_002_name':
        return localizations.exercise_core_002_name;
      case 'exercise_core_002_description':
        return localizations.exercise_core_002_description;
      case 'exercise_core_002_beginner_tips':
        return localizations.exercise_core_002_beginner_tips;
      case 'exercise_core_003_name':
        return localizations.exercise_core_003_name;
      case 'exercise_core_003_description':
        return localizations.exercise_core_003_description;
      case 'exercise_core_003_beginner_tips':
        return localizations.exercise_core_003_beginner_tips;
      case 'exercise_core_004_name':
        return localizations.exercise_core_004_name;
      case 'exercise_core_004_description':
        return localizations.exercise_core_004_description;
      case 'exercise_core_004_beginner_tips':
        return localizations.exercise_core_004_beginner_tips;
      case 'exercise_core_005_name':
        return localizations.exercise_core_005_name;
      case 'exercise_core_005_description':
        return localizations.exercise_core_005_description;
      case 'exercise_core_005_beginner_tips':
        return localizations.exercise_core_005_beginner_tips;
      case 'exercise_core_006_name':
        return localizations.exercise_core_006_name;
      case 'exercise_core_006_description':
        return localizations.exercise_core_006_description;
      case 'exercise_core_006_beginner_tips':
        return localizations.exercise_core_006_beginner_tips;
      case 'exercise_core_007_name':
        return localizations.exercise_core_007_name;
      case 'exercise_core_007_description':
        return localizations.exercise_core_007_description;
      case 'exercise_core_007_beginner_tips':
        return localizations.exercise_core_007_beginner_tips;
      case 'exercise_core_008_name':
        return localizations.exercise_core_008_name;
      case 'exercise_core_008_description':
        return localizations.exercise_core_008_description;
      case 'exercise_core_008_beginner_tips':
        return localizations.exercise_core_008_beginner_tips;
      case 'exercise_core_009_name':
        return localizations.exercise_core_009_name;
      case 'exercise_core_009_description':
        return localizations.exercise_core_009_description;
      case 'exercise_core_009_beginner_tips':
        return localizations.exercise_core_009_beginner_tips;
      case 'exercise_core_010_name':
        return localizations.exercise_core_010_name;
      case 'exercise_core_010_description':
        return localizations.exercise_core_010_description;
      case 'exercise_core_010_beginner_tips':
        return localizations.exercise_core_010_beginner_tips;
      case 'exercise_core_011_name':
        return localizations.exercise_core_011_name;
      case 'exercise_core_011_description':
        return localizations.exercise_core_011_description;
      case 'exercise_core_011_beginner_tips':
        return localizations.exercise_core_011_beginner_tips;
      case 'exercise_core_012_name':
        return localizations.exercise_core_012_name;
      case 'exercise_core_012_description':
        return localizations.exercise_core_012_description;
      case 'exercise_core_012_beginner_tips':
        return localizations.exercise_core_012_beginner_tips;
      case 'exercise_core_013_name':
        return localizations.exercise_core_013_name;
      case 'exercise_core_013_description':
        return localizations.exercise_core_013_description;
      case 'exercise_core_013_beginner_tips':
        return localizations.exercise_core_013_beginner_tips;
      case 'exercise_core_014_name':
        return localizations.exercise_core_014_name;
      case 'exercise_core_014_description':
        return localizations.exercise_core_014_description;
      case 'exercise_core_014_beginner_tips':
        return localizations.exercise_core_014_beginner_tips;
      case 'exercise_core_015_name':
        return localizations.exercise_core_015_name;
      case 'exercise_core_015_description':
        return localizations.exercise_core_015_description;
      case 'exercise_core_015_beginner_tips':
        return localizations.exercise_core_015_beginner_tips;
      case 'exercise_core_016_name':
        return localizations.exercise_core_016_name;
      case 'exercise_core_016_description':
        return localizations.exercise_core_016_description;
      case 'exercise_core_016_beginner_tips':
        return localizations.exercise_core_016_beginner_tips;
      case 'exercise_core_017_name':
        return localizations.exercise_core_017_name;
      case 'exercise_core_017_description':
        return localizations.exercise_core_017_description;
      case 'exercise_core_017_beginner_tips':
        return localizations.exercise_core_017_beginner_tips;
      case 'exercise_core_018_name':
        return localizations.exercise_core_018_name;
      case 'exercise_core_018_description':
        return localizations.exercise_core_018_description;
      case 'exercise_core_018_beginner_tips':
        return localizations.exercise_core_018_beginner_tips;
      case 'exercise_core_019_name':
        return localizations.exercise_core_019_name;
      case 'exercise_core_019_description':
        return localizations.exercise_core_019_description;
      case 'exercise_core_019_beginner_tips':
        return localizations.exercise_core_019_beginner_tips;
      case 'exercise_core_020_name':
        return localizations.exercise_core_020_name;
      case 'exercise_core_020_description':
        return localizations.exercise_core_020_description;
      case 'exercise_core_020_beginner_tips':
        return localizations.exercise_core_020_beginner_tips;
      case 'exercise_legs_001_name':
        return localizations.exercise_legs_001_name;
      case 'exercise_legs_001_description':
        return localizations.exercise_legs_001_description;
      case 'exercise_legs_001_beginner_tips':
        return localizations.exercise_legs_001_beginner_tips;
      case 'exercise_legs_002_name':
        return localizations.exercise_legs_002_name;
      case 'exercise_legs_002_description':
        return localizations.exercise_legs_002_description;
      case 'exercise_legs_002_beginner_tips':
        return localizations.exercise_legs_002_beginner_tips;
      case 'exercise_legs_003_name':
        return localizations.exercise_legs_003_name;
      case 'exercise_legs_003_description':
        return localizations.exercise_legs_003_description;
      case 'exercise_legs_003_beginner_tips':
        return localizations.exercise_legs_003_beginner_tips;
      case 'exercise_legs_004_name':
        return localizations.exercise_legs_004_name;
      case 'exercise_legs_004_description':
        return localizations.exercise_legs_004_description;
      case 'exercise_legs_004_beginner_tips':
        return localizations.exercise_legs_004_beginner_tips;
      case 'exercise_legs_005_name':
        return localizations.exercise_legs_005_name;
      case 'exercise_legs_005_description':
        return localizations.exercise_legs_005_description;
      case 'exercise_legs_005_beginner_tips':
        return localizations.exercise_legs_005_beginner_tips;
      case 'exercise_legs_006_name':
        return localizations.exercise_legs_006_name;
      case 'exercise_legs_006_description':
        return localizations.exercise_legs_006_description;
      case 'exercise_legs_006_beginner_tips':
        return localizations.exercise_legs_006_beginner_tips;
      case 'exercise_legs_007_name':
        return localizations.exercise_legs_007_name;
      case 'exercise_legs_007_description':
        return localizations.exercise_legs_007_description;
      case 'exercise_legs_007_beginner_tips':
        return localizations.exercise_legs_007_beginner_tips;
      case 'exercise_legs_008_name':
        return localizations.exercise_legs_008_name;
      case 'exercise_legs_008_description':
        return localizations.exercise_legs_008_description;
      case 'exercise_legs_008_beginner_tips':
        return localizations.exercise_legs_008_beginner_tips;
      case 'exercise_legs_009_name':
        return localizations.exercise_legs_009_name;
      case 'exercise_legs_009_description':
        return localizations.exercise_legs_009_description;
      case 'exercise_legs_009_beginner_tips':
        return localizations.exercise_legs_009_beginner_tips;
      case 'exercise_legs_010_name':
        return localizations.exercise_legs_010_name;
      case 'exercise_legs_010_description':
        return localizations.exercise_legs_010_description;
      case 'exercise_legs_010_beginner_tips':
        return localizations.exercise_legs_010_beginner_tips;
      case 'exercise_legs_011_name':
        return localizations.exercise_legs_011_name;
      case 'exercise_legs_011_description':
        return localizations.exercise_legs_011_description;
      case 'exercise_legs_011_beginner_tips':
        return localizations.exercise_legs_011_beginner_tips;
      case 'exercise_legs_012_name':
        return localizations.exercise_legs_012_name;
      case 'exercise_legs_012_description':
        return localizations.exercise_legs_012_description;
      case 'exercise_legs_012_beginner_tips':
        return localizations.exercise_legs_012_beginner_tips;
      case 'exercise_legs_013_name':
        return localizations.exercise_legs_013_name;
      case 'exercise_legs_013_description':
        return localizations.exercise_legs_013_description;
      case 'exercise_legs_013_beginner_tips':
        return localizations.exercise_legs_013_beginner_tips;
      case 'exercise_legs_014_name':
        return localizations.exercise_legs_014_name;
      case 'exercise_legs_014_description':
        return localizations.exercise_legs_014_description;
      case 'exercise_legs_014_beginner_tips':
        return localizations.exercise_legs_014_beginner_tips;
      case 'exercise_legs_015_name':
        return localizations.exercise_legs_015_name;
      case 'exercise_legs_015_description':
        return localizations.exercise_legs_015_description;
      case 'exercise_legs_015_beginner_tips':
        return localizations.exercise_legs_015_beginner_tips;
      case 'exercise_legs_016_name':
        return localizations.exercise_legs_016_name;
      case 'exercise_legs_016_description':
        return localizations.exercise_legs_016_description;
      case 'exercise_legs_016_beginner_tips':
        return localizations.exercise_legs_016_beginner_tips;
      case 'exercise_legs_017_name':
        return localizations.exercise_legs_017_name;
      case 'exercise_legs_017_description':
        return localizations.exercise_legs_017_description;
      case 'exercise_legs_017_beginner_tips':
        return localizations.exercise_legs_017_beginner_tips;
      case 'exercise_legs_018_name':
        return localizations.exercise_legs_018_name;
      case 'exercise_legs_018_description':
        return localizations.exercise_legs_018_description;
      case 'exercise_legs_018_beginner_tips':
        return localizations.exercise_legs_018_beginner_tips;
      case 'exercise_legs_019_name':
        return localizations.exercise_legs_019_name;
      case 'exercise_legs_019_description':
        return localizations.exercise_legs_019_description;
      case 'exercise_legs_019_beginner_tips':
        return localizations.exercise_legs_019_beginner_tips;
      case 'exercise_legs_020_name':
        return localizations.exercise_legs_020_name;
      case 'exercise_legs_020_description':
        return localizations.exercise_legs_020_description;
      case 'exercise_legs_020_beginner_tips':
        return localizations.exercise_legs_020_beginner_tips;
      case 'exercise_legs_021_name':
        return localizations.exercise_legs_021_name;
      case 'exercise_legs_021_description':
        return localizations.exercise_legs_021_description;
      case 'exercise_legs_021_beginner_tips':
        return localizations.exercise_legs_021_beginner_tips;
      case 'exercise_legs_022_name':
        return localizations.exercise_legs_022_name;
      case 'exercise_legs_022_description':
        return localizations.exercise_legs_022_description;
      case 'exercise_legs_022_beginner_tips':
        return localizations.exercise_legs_022_beginner_tips;
      case 'exercise_legs_023_name':
        return localizations.exercise_legs_023_name;
      case 'exercise_legs_023_description':
        return localizations.exercise_legs_023_description;
      case 'exercise_legs_023_beginner_tips':
        return localizations.exercise_legs_023_beginner_tips;
      case 'exercise_legs_024_name':
        return localizations.exercise_legs_024_name;
      case 'exercise_legs_024_description':
        return localizations.exercise_legs_024_description;
      case 'exercise_legs_024_beginner_tips':
        return localizations.exercise_legs_024_beginner_tips;
      case 'exercise_legs_025_name':
        return localizations.exercise_legs_025_name;
      case 'exercise_legs_025_description':
        return localizations.exercise_legs_025_description;
      case 'exercise_legs_025_beginner_tips':
        return localizations.exercise_legs_025_beginner_tips;
      case 'exercise_pull_001_name':
        return localizations.exercise_pull_001_name;
      case 'exercise_pull_001_description':
        return localizations.exercise_pull_001_description;
      case 'exercise_pull_001_beginner_tips':
        return localizations.exercise_pull_001_beginner_tips;
      case 'exercise_pull_002_name':
        return localizations.exercise_pull_002_name;
      case 'exercise_pull_002_description':
        return localizations.exercise_pull_002_description;
      case 'exercise_pull_002_beginner_tips':
        return localizations.exercise_pull_002_beginner_tips;
      case 'exercise_pull_003_name':
        return localizations.exercise_pull_003_name;
      case 'exercise_pull_003_description':
        return localizations.exercise_pull_003_description;
      case 'exercise_pull_003_beginner_tips':
        return localizations.exercise_pull_003_beginner_tips;
      case 'exercise_pull_004_name':
        return localizations.exercise_pull_004_name;
      case 'exercise_pull_004_description':
        return localizations.exercise_pull_004_description;
      case 'exercise_pull_004_beginner_tips':
        return localizations.exercise_pull_004_beginner_tips;
      case 'exercise_pull_005_name':
        return localizations.exercise_pull_005_name;
      case 'exercise_pull_005_description':
        return localizations.exercise_pull_005_description;
      case 'exercise_pull_005_beginner_tips':
        return localizations.exercise_pull_005_beginner_tips;
      case 'exercise_pull_006_name':
        return localizations.exercise_pull_006_name;
      case 'exercise_pull_006_description':
        return localizations.exercise_pull_006_description;
      case 'exercise_pull_006_beginner_tips':
        return localizations.exercise_pull_006_beginner_tips;
      case 'exercise_pull_007_name':
        return localizations.exercise_pull_007_name;
      case 'exercise_pull_007_description':
        return localizations.exercise_pull_007_description;
      case 'exercise_pull_007_beginner_tips':
        return localizations.exercise_pull_007_beginner_tips;
      case 'exercise_pull_008_name':
        return localizations.exercise_pull_008_name;
      case 'exercise_pull_008_description':
        return localizations.exercise_pull_008_description;
      case 'exercise_pull_008_beginner_tips':
        return localizations.exercise_pull_008_beginner_tips;
      case 'exercise_pull_009_name':
        return localizations.exercise_pull_009_name;
      case 'exercise_pull_009_description':
        return localizations.exercise_pull_009_description;
      case 'exercise_pull_009_beginner_tips':
        return localizations.exercise_pull_009_beginner_tips;
      case 'exercise_pull_010_name':
        return localizations.exercise_pull_010_name;
      case 'exercise_pull_010_description':
        return localizations.exercise_pull_010_description;
      case 'exercise_pull_010_beginner_tips':
        return localizations.exercise_pull_010_beginner_tips;
      case 'exercise_pull_011_name':
        return localizations.exercise_pull_011_name;
      case 'exercise_pull_011_description':
        return localizations.exercise_pull_011_description;
      case 'exercise_pull_011_beginner_tips':
        return localizations.exercise_pull_011_beginner_tips;
      case 'exercise_pull_012_name':
        return localizations.exercise_pull_012_name;
      case 'exercise_pull_012_description':
        return localizations.exercise_pull_012_description;
      case 'exercise_pull_012_beginner_tips':
        return localizations.exercise_pull_012_beginner_tips;
      case 'exercise_pull_013_name':
        return localizations.exercise_pull_013_name;
      case 'exercise_pull_013_description':
        return localizations.exercise_pull_013_description;
      case 'exercise_pull_013_beginner_tips':
        return localizations.exercise_pull_013_beginner_tips;
      case 'exercise_pull_014_name':
        return localizations.exercise_pull_014_name;
      case 'exercise_pull_014_description':
        return localizations.exercise_pull_014_description;
      case 'exercise_pull_014_beginner_tips':
        return localizations.exercise_pull_014_beginner_tips;
      case 'exercise_pull_015_name':
        return localizations.exercise_pull_015_name;
      case 'exercise_pull_015_description':
        return localizations.exercise_pull_015_description;
      case 'exercise_pull_015_beginner_tips':
        return localizations.exercise_pull_015_beginner_tips;
      case 'exercise_pull_016_name':
        return localizations.exercise_pull_016_name;
      case 'exercise_pull_016_description':
        return localizations.exercise_pull_016_description;
      case 'exercise_pull_016_beginner_tips':
        return localizations.exercise_pull_016_beginner_tips;
      case 'exercise_pull_017_name':
        return localizations.exercise_pull_017_name;
      case 'exercise_pull_017_description':
        return localizations.exercise_pull_017_description;
      case 'exercise_pull_017_beginner_tips':
        return localizations.exercise_pull_017_beginner_tips;
      case 'exercise_pull_018_name':
        return localizations.exercise_pull_018_name;
      case 'exercise_pull_018_description':
        return localizations.exercise_pull_018_description;
      case 'exercise_pull_018_beginner_tips':
        return localizations.exercise_pull_018_beginner_tips;
      case 'exercise_pull_019_name':
        return localizations.exercise_pull_019_name;
      case 'exercise_pull_019_description':
        return localizations.exercise_pull_019_description;
      case 'exercise_pull_019_beginner_tips':
        return localizations.exercise_pull_019_beginner_tips;
      case 'exercise_pull_020_name':
        return localizations.exercise_pull_020_name;
      case 'exercise_pull_020_description':
        return localizations.exercise_pull_020_description;
      case 'exercise_pull_020_beginner_tips':
        return localizations.exercise_pull_020_beginner_tips;
      case 'exercise_push_001_name':
        return localizations.exercise_push_001_name;
      case 'exercise_push_001_description':
        return localizations.exercise_push_001_description;
      case 'exercise_push_001_beginner_tips':
        return localizations.exercise_push_001_beginner_tips;
      case 'exercise_push_002_name':
        return localizations.exercise_push_002_name;
      case 'exercise_push_002_description':
        return localizations.exercise_push_002_description;
      case 'exercise_push_002_beginner_tips':
        return localizations.exercise_push_002_beginner_tips;
      case 'exercise_push_003_name':
        return localizations.exercise_push_003_name;
      case 'exercise_push_003_description':
        return localizations.exercise_push_003_description;
      case 'exercise_push_003_beginner_tips':
        return localizations.exercise_push_003_beginner_tips;
      case 'exercise_push_004_name':
        return localizations.exercise_push_004_name;
      case 'exercise_push_004_description':
        return localizations.exercise_push_004_description;
      case 'exercise_push_004_beginner_tips':
        return localizations.exercise_push_004_beginner_tips;
      case 'exercise_push_005_name':
        return localizations.exercise_push_005_name;
      case 'exercise_push_005_description':
        return localizations.exercise_push_005_description;
      case 'exercise_push_005_beginner_tips':
        return localizations.exercise_push_005_beginner_tips;
      case 'exercise_push_006_name':
        return localizations.exercise_push_006_name;
      case 'exercise_push_006_description':
        return localizations.exercise_push_006_description;
      case 'exercise_push_006_beginner_tips':
        return localizations.exercise_push_006_beginner_tips;
      case 'exercise_push_007_name':
        return localizations.exercise_push_007_name;
      case 'exercise_push_007_description':
        return localizations.exercise_push_007_description;
      case 'exercise_push_007_beginner_tips':
        return localizations.exercise_push_007_beginner_tips;
      case 'exercise_push_008_name':
        return localizations.exercise_push_008_name;
      case 'exercise_push_008_description':
        return localizations.exercise_push_008_description;
      case 'exercise_push_008_beginner_tips':
        return localizations.exercise_push_008_beginner_tips;
      case 'exercise_push_009_name':
        return localizations.exercise_push_009_name;
      case 'exercise_push_009_description':
        return localizations.exercise_push_009_description;
      case 'exercise_push_009_beginner_tips':
        return localizations.exercise_push_009_beginner_tips;
      case 'exercise_push_010_name':
        return localizations.exercise_push_010_name;
      case 'exercise_push_010_description':
        return localizations.exercise_push_010_description;
      case 'exercise_push_010_beginner_tips':
        return localizations.exercise_push_010_beginner_tips;
      case 'exercise_push_011_name':
        return localizations.exercise_push_011_name;
      case 'exercise_push_011_description':
        return localizations.exercise_push_011_description;
      case 'exercise_push_011_beginner_tips':
        return localizations.exercise_push_011_beginner_tips;
      case 'exercise_push_012_name':
        return localizations.exercise_push_012_name;
      case 'exercise_push_012_description':
        return localizations.exercise_push_012_description;
      case 'exercise_push_012_beginner_tips':
        return localizations.exercise_push_012_beginner_tips;
      case 'exercise_push_013_name':
        return localizations.exercise_push_013_name;
      case 'exercise_push_013_description':
        return localizations.exercise_push_013_description;
      case 'exercise_push_013_beginner_tips':
        return localizations.exercise_push_013_beginner_tips;
      case 'exercise_push_014_name':
        return localizations.exercise_push_014_name;
      case 'exercise_push_014_description':
        return localizations.exercise_push_014_description;
      case 'exercise_push_014_beginner_tips':
        return localizations.exercise_push_014_beginner_tips;
      case 'exercise_push_015_name':
        return localizations.exercise_push_015_name;
      case 'exercise_push_015_description':
        return localizations.exercise_push_015_description;
      case 'exercise_push_015_beginner_tips':
        return localizations.exercise_push_015_beginner_tips;
      case 'exercise_push_016_name':
        return localizations.exercise_push_016_name;
      case 'exercise_push_016_description':
        return localizations.exercise_push_016_description;
      case 'exercise_push_016_beginner_tips':
        return localizations.exercise_push_016_beginner_tips;
      case 'exercise_push_017_name':
        return localizations.exercise_push_017_name;
      case 'exercise_push_017_description':
        return localizations.exercise_push_017_description;
      case 'exercise_push_017_beginner_tips':
        return localizations.exercise_push_017_beginner_tips;
      case 'exercise_push_018_name':
        return localizations.exercise_push_018_name;
      case 'exercise_push_018_description':
        return localizations.exercise_push_018_description;
      case 'exercise_push_018_beginner_tips':
        return localizations.exercise_push_018_beginner_tips;
      case 'exercise_push_019_name':
        return localizations.exercise_push_019_name;
      case 'exercise_push_019_description':
        return localizations.exercise_push_019_description;
      case 'exercise_push_019_beginner_tips':
        return localizations.exercise_push_019_beginner_tips;
      case 'exercise_push_020_name':
        return localizations.exercise_push_020_name;
      case 'exercise_push_020_description':
        return localizations.exercise_push_020_description;
      case 'exercise_push_020_beginner_tips':
        return localizations.exercise_push_020_beginner_tips;
      default:
        return null;
    }
  }

  static String? getName(AppLocalizations localizations, String exerciseId) {
    return getString(localizations, 'exercise_${exerciseId}_name');
  }

  static String? getDescription(
    AppLocalizations localizations,
    String exerciseId,
  ) {
    return getString(localizations, 'exercise_${exerciseId}_description');
  }

  static String? getBeginnerTips(
    AppLocalizations localizations,
    String exerciseId,
  ) {
    return getString(localizations, 'exercise_${exerciseId}_beginner_tips');
  }
}
