// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATAIITmrctbyyWg4aidYgKaWzW68h9K_s',
    appId: '1:358773329890:web:75dea3d3f7dcc69c40f3bb',
    messagingSenderId: '358773329890',
    projectId: 'workinfit',
    authDomain: 'workinfit.firebaseapp.com',
    storageBucket: 'workinfit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBjFOX_uLSaPLYxhSnqBY_IBvzRG3vqE',
    appId: '1:358773329890:android:714281f028584c7340f3bb',
    messagingSenderId: '358773329890',
    projectId: 'workinfit',
    storageBucket: 'workinfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_HRNLyarvKBwlepB_pxCSlWZiVd4Ko00',
    appId: '1:358773329890:ios:e5d0f1036d6363bb40f3bb',
    messagingSenderId: '358773329890',
    projectId: 'workinfit',
    storageBucket: 'workinfit.firebasestorage.app',
    androidClientId: '358773329890-o89bhe32jfbb2bp8o2cbd0iui36e57rj.apps.googleusercontent.com',
    iosClientId: '358773329890-s65s5ak7f8gbo9aiqteja6s9ccfjee9q.apps.googleusercontent.com',
    iosBundleId: 'com.workinfit.workinFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_HRNLyarvKBwlepB_pxCSlWZiVd4Ko00',
    appId: '1:358773329890:ios:e5d0f1036d6363bb40f3bb',
    messagingSenderId: '358773329890',
    projectId: 'workinfit',
    storageBucket: 'workinfit.firebasestorage.app',
    androidClientId: '358773329890-o89bhe32jfbb2bp8o2cbd0iui36e57rj.apps.googleusercontent.com',
    iosClientId: '358773329890-s65s5ak7f8gbo9aiqteja6s9ccfjee9q.apps.googleusercontent.com',
    iosBundleId: 'com.workinfit.workinFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATAIITmrctbyyWg4aidYgKaWzW68h9K_s',
    appId: '1:358773329890:web:8c8ea162dde1aa2e40f3bb',
    messagingSenderId: '358773329890',
    projectId: 'workinfit',
    authDomain: 'workinfit.firebaseapp.com',
    storageBucket: 'workinfit.firebasestorage.app',
  );
}
