// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXVKHqigDcsONeWZgjqEorBHAFHYsHOu4',
    appId: '1:22533708652:web:24bde275b741a41568b149',
    messagingSenderId: '22533708652',
    projectId: 'sport-app-123',
    authDomain: 'sport-app-123.firebaseapp.com',
    storageBucket: 'sport-app-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmEn5w3IyHMeAj58ojViprspOt1QT2vdE',
    appId: '1:22533708652:android:d5a46ce4645a598568b149',
    messagingSenderId: '22533708652',
    projectId: 'sport-app-123',
    storageBucket: 'sport-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoHaCBRq-IVvL10P_L47xWy1o0Sogqww',
    appId: '1:22533708652:ios:b447419239d15d9968b149',
    messagingSenderId: '22533708652',
    projectId: 'sport-app-123',
    storageBucket: 'sport-app-123.firebasestorage.app',
    iosBundleId: 'com.damienp.sportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoHaCBRq-IVvL10P_L47xWy1o0Sogqww',
    appId: '1:22533708652:ios:b447419239d15d9968b149',
    messagingSenderId: '22533708652',
    projectId: 'sport-app-123',
    storageBucket: 'sport-app-123.firebasestorage.app',
    iosBundleId: 'com.damienp.sportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXVKHqigDcsONeWZgjqEorBHAFHYsHOu4',
    appId: '1:22533708652:web:5b2fbe97b230508468b149',
    messagingSenderId: '22533708652',
    projectId: 'sport-app-123',
    authDomain: 'sport-app-123.firebaseapp.com',
    storageBucket: 'sport-app-123.firebasestorage.app',
  );

}