// Mocks generated by Mockito 5.4.4 from annotations
// in workin_fit/test/unit/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:connectivity_plus/connectivity_plus.dart' as _i10;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:workin_fit/models/active_program_state.dart' as _i4;
import 'package:workin_fit/models/exercise.dart' as _i5;
import 'package:workin_fit/models/program.dart' as _i7;
import 'package:workin_fit/models/session.dart' as _i6;
import 'package:workin_fit/services/firestore_service.dart' as _i2;
import 'package:workin_fit/services/local_storage_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createOrUpdateUserProfile({
    required String? userId,
    required String? username,
    required String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrUpdateUserProfile,
          [],
          {
            #userId: userId,
            #username: username,
            #email: email,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Stream<_i4.ActiveProgramState?> activeProgramStateStream(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #activeProgramStateStream,
          [userId],
        ),
        returnValue: _i3.Stream<_i4.ActiveProgramState?>.empty(),
      ) as _i3.Stream<_i4.ActiveProgramState?>);

  @override
  _i3.Future<_i4.ActiveProgramState?> getActiveProgramState(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveProgramState,
          [userId],
        ),
        returnValue: _i3.Future<_i4.ActiveProgramState?>.value(),
      ) as _i3.Future<_i4.ActiveProgramState?>);

  @override
  _i3.Future<void> subscribeUserToProgram({
    required String? userId,
    required String? programId,
    required DateTime? startDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeUserToProgram,
          [],
          {
            #userId: userId,
            #programId: programId,
            #startDate: startDate,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> unsubscribeUserFromProgram(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsubscribeUserFromProgram,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Exercise>> getExercises() => (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Exercise>>.value(<_i5.Exercise>[]),
      ) as _i3.Future<List<_i5.Exercise>>);

  @override
  _i3.Future<_i5.Exercise?> getExerciseById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [id],
        ),
        returnValue: _i3.Future<_i5.Exercise?>.value(),
      ) as _i3.Future<_i5.Exercise?>);

  @override
  _i3.Future<List<_i5.Exercise>> searchExercises(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchExercises,
          [query],
        ),
        returnValue: _i3.Future<List<_i5.Exercise>>.value(<_i5.Exercise>[]),
      ) as _i3.Future<List<_i5.Exercise>>);

  @override
  _i3.Stream<List<_i5.Exercise>> exercisesStream() => (super.noSuchMethod(
        Invocation.method(
          #exercisesStream,
          [],
        ),
        returnValue: _i3.Stream<List<_i5.Exercise>>.empty(),
      ) as _i3.Stream<List<_i5.Exercise>>);

  @override
  _i3.Future<List<_i6.Session>> getSessions(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [userId],
        ),
        returnValue: _i3.Future<List<_i6.Session>>.value(<_i6.Session>[]),
      ) as _i3.Future<List<_i6.Session>>);

  @override
  _i3.Future<_i6.Session?> getSessionById(
    String? userId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionById,
          [
            userId,
            sessionId,
          ],
        ),
        returnValue: _i3.Future<_i6.Session?>.value(),
      ) as _i3.Future<_i6.Session?>);

  @override
  _i3.Future<_i6.Session?> getSessionByOwner(
    String? ownerId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionByOwner,
          [
            ownerId,
            sessionId,
          ],
        ),
        returnValue: _i3.Future<_i6.Session?>.value(),
      ) as _i3.Future<_i6.Session?>);

  @override
  _i3.Future<void> createSession(
    String? userId,
    _i6.Session? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [
            userId,
            session,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSession(
    String? userId,
    _i6.Session? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [
            userId,
            session,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSession(
    String? userId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [
            userId,
            sessionId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i6.Session>> userSessionsStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #userSessionsStream,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i6.Session>>.empty(),
      ) as _i3.Stream<List<_i6.Session>>);

  @override
  _i3.Future<List<_i6.Session>> getPresetSessions() => (super.noSuchMethod(
        Invocation.method(
          #getPresetSessions,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Session>>.value(<_i6.Session>[]),
      ) as _i3.Future<List<_i6.Session>>);

  @override
  _i3.Future<List<_i7.Program>> getPrograms() => (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [],
        ),
        returnValue: _i3.Future<List<_i7.Program>>.value(<_i7.Program>[]),
      ) as _i3.Future<List<_i7.Program>>);

  @override
  _i3.Future<_i7.Program?> getProgramById(
    String? programId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgramById,
          [programId],
          {#userId: userId},
        ),
        returnValue: _i3.Future<_i7.Program?>.value(),
      ) as _i3.Future<_i7.Program?>);

  @override
  _i3.Stream<_i7.Program?> subscribeToProgram(
    String? programId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToProgram,
          [programId],
          {#userId: userId},
        ),
        returnValue: _i3.Stream<_i7.Program?>.empty(),
      ) as _i3.Stream<_i7.Program?>);

  @override
  _i3.Future<List<_i7.Program>> getUserPrograms(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPrograms,
          [userId],
        ),
        returnValue: _i3.Future<List<_i7.Program>>.value(<_i7.Program>[]),
      ) as _i3.Future<List<_i7.Program>>);

  @override
  _i3.Future<void> createProgram(
    String? userId,
    _i7.Program? program,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProgram,
          [
            userId,
            program,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateProgram(
    String? userId,
    _i7.Program? program,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgram,
          [
            userId,
            program,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProgram(
    String? userId,
    String? programId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProgram,
          [
            userId,
            programId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getWorkoutHistory({
    required String? userId,
    int? limit = 180,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutHistory,
          [],
          {
            #userId: userId,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getMonthlyExerciseAggregates({
    required String? userId,
    required String? monthKey,
    int? limit = 2000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyExerciseAggregates,
          [],
          {
            #userId: userId,
            #monthKey: monthKey,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getMonthlyWorkoutSummary({
    required String? userId,
    required String? monthKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyWorkoutSummary,
          [],
          {
            #userId: userId,
            #monthKey: monthKey,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<String> saveWorkoutHistory({
    required String? userId,
    required String? sessionId,
    required DateTime? completedAt,
    required int? duration,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkoutHistory,
          [],
          {
            #userId: userId,
            #sessionId: sessionId,
            #completedAt: completedAt,
            #duration: duration,
            #metadata: metadata,
          },
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #saveWorkoutHistory,
            [],
            {
              #userId: userId,
              #sessionId: sessionId,
              #completedAt: completedAt,
              #duration: duration,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<Map<String, dynamic>> getStreakData({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakData,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Set<String>> getUnlockedAchievementIds(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnlockedAchievementIds,
          [userId],
        ),
        returnValue: _i3.Future<Set<String>>.value(<String>{}),
      ) as _i3.Future<Set<String>>);

  @override
  _i3.Future<void> unlockAchievement({
    required String? userId,
    required String? achievementId,
    required DateTime? unlockedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlockAchievement,
          [],
          {
            #userId: userId,
            #achievementId: achievementId,
            #unlockedAt: unlockedAt,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getTotalDoneReps(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getTotalDoneReps,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalWorkoutCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getTotalWorkoutCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getProgramsCompleted(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getProgramsCompleted,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> incrementProgramsCompleted(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementProgramsCompleted,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> getChallengeCompletion({
    required String? userId,
    required String? challengeId,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChallengeCompletion,
          [],
          {
            #userId: userId,
            #challengeId: challengeId,
            #date: date,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setChallengeCompleted({
    required String? userId,
    required String? challengeId,
    required DateTime? date,
    required bool? completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setChallengeCompleted,
          [],
          {
            #userId: userId,
            #challengeId: challengeId,
            #date: date,
            #completed: completed,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i9.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheExercises(List<_i5.Exercise>? exercises) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheExercises,
          [exercises],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> mergeCachedExercises(List<_i5.Exercise>? exercises) =>
      (super.noSuchMethod(
        Invocation.method(
          #mergeCachedExercises,
          [exercises],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.Exercise>> getCachedExercises() => (super.noSuchMethod(
        Invocation.method(
          #getCachedExercises,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Exercise>>.value(<_i5.Exercise>[]),
      ) as _i3.Future<List<_i5.Exercise>>);

  @override
  _i3.Future<_i5.Exercise?> getCachedExercise(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedExercise,
          [id],
        ),
        returnValue: _i3.Future<_i5.Exercise?>.value(),
      ) as _i3.Future<_i5.Exercise?>);

  @override
  _i3.Future<void> saveSessionLocally(_i6.Session? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSessionLocally,
          [session],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.Session>> getLocalSessions() => (super.noSuchMethod(
        Invocation.method(
          #getLocalSessions,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Session>>.value(<_i6.Session>[]),
      ) as _i3.Future<List<_i6.Session>>);

  @override
  _i3.Future<_i6.Session?> getLocalSession(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalSession,
          [sessionId],
        ),
        returnValue: _i3.Future<_i6.Session?>.value(),
      ) as _i3.Future<_i6.Session?>);

  @override
  _i3.Future<void> deleteLocalSession(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocalSession,
          [sessionId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearLocalSessions() => (super.noSuchMethod(
        Invocation.method(
          #clearLocalSessions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveProgramLocally(_i7.Program? program) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProgramLocally,
          [program],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Program>> getLocalPrograms() => (super.noSuchMethod(
        Invocation.method(
          #getLocalPrograms,
          [],
        ),
        returnValue: _i3.Future<List<_i7.Program>>.value(<_i7.Program>[]),
      ) as _i3.Future<List<_i7.Program>>);

  @override
  _i3.Future<_i7.Program?> getLocalProgram(String? programId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalProgram,
          [programId],
        ),
        returnValue: _i3.Future<_i7.Program?>.value(),
      ) as _i3.Future<_i7.Program?>);

  @override
  _i3.Future<void> cachePrograms(List<_i7.Program>? programs) =>
      (super.noSuchMethod(
        Invocation.method(
          #cachePrograms,
          [programs],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLocalProgram(String? programId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocalProgram,
          [programId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearLocalPrograms() => (super.noSuchMethod(
        Invocation.method(
          #clearLocalPrograms,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markForSync(
    String? itemId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markForSync,
          [
            itemId,
            type,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getPendingSync() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSync,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> clearSyncItem(
    String? id,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearSyncItem,
          [
            id,
            type,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearSyncQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearSyncQueue,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i10.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i11.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i3.Stream<List<_i11.ConnectivityResult>>.empty(),
      ) as _i3.Stream<List<_i11.ConnectivityResult>>);

  @override
  _i3.Future<List<_i11.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i3.Future<List<_i11.ConnectivityResult>>.value(
            <_i11.ConnectivityResult>[]),
      ) as _i3.Future<List<_i11.ConnectivityResult>>);
}
