// Mocks generated by Mockito 5.4.4 from annotations
// in workin_fit/test/unit/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:workin_fit/models/active_program_state.dart' as _i5;
import 'package:workin_fit/models/exercise.dart' as _i6;
import 'package:workin_fit/models/program.dart' as _i8;
import 'package:workin_fit/models/session.dart' as _i7;
import 'package:workin_fit/repository/auth_repository.dart' as _i10;
import 'package:workin_fit/services/firestore_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createOrUpdateUserProfile({
    required String? userId,
    required String? username,
    required String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrUpdateUserProfile,
          [],
          {
            #userId: userId,
            #username: username,
            #email: email,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Stream<_i5.ActiveProgramState?> activeProgramStateStream(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #activeProgramStateStream,
          [userId],
        ),
        returnValue: _i4.Stream<_i5.ActiveProgramState?>.empty(),
      ) as _i4.Stream<_i5.ActiveProgramState?>);

  @override
  _i4.Future<_i5.ActiveProgramState?> getActiveProgramState(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveProgramState,
          [userId],
        ),
        returnValue: _i4.Future<_i5.ActiveProgramState?>.value(),
      ) as _i4.Future<_i5.ActiveProgramState?>);

  @override
  _i4.Future<void> subscribeUserToProgram({
    required String? userId,
    required String? programId,
    required DateTime? startDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeUserToProgram,
          [],
          {
            #userId: userId,
            #programId: programId,
            #startDate: startDate,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unsubscribeUserFromProgram(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsubscribeUserFromProgram,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Exercise>> getExercises() => (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Exercise>>.value(<_i6.Exercise>[]),
      ) as _i4.Future<List<_i6.Exercise>>);

  @override
  _i4.Future<_i6.Exercise?> getExerciseById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [id],
        ),
        returnValue: _i4.Future<_i6.Exercise?>.value(),
      ) as _i4.Future<_i6.Exercise?>);

  @override
  _i4.Future<List<_i6.Exercise>> searchExercises(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchExercises,
          [query],
        ),
        returnValue: _i4.Future<List<_i6.Exercise>>.value(<_i6.Exercise>[]),
      ) as _i4.Future<List<_i6.Exercise>>);

  @override
  _i4.Stream<List<_i6.Exercise>> exercisesStream() => (super.noSuchMethod(
        Invocation.method(
          #exercisesStream,
          [],
        ),
        returnValue: _i4.Stream<List<_i6.Exercise>>.empty(),
      ) as _i4.Stream<List<_i6.Exercise>>);

  @override
  _i4.Future<List<_i7.Session>> getSessions(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [userId],
        ),
        returnValue: _i4.Future<List<_i7.Session>>.value(<_i7.Session>[]),
      ) as _i4.Future<List<_i7.Session>>);

  @override
  _i4.Future<_i7.Session?> getSessionById(
    String? userId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionById,
          [
            userId,
            sessionId,
          ],
        ),
        returnValue: _i4.Future<_i7.Session?>.value(),
      ) as _i4.Future<_i7.Session?>);

  @override
  _i4.Future<_i7.Session?> getSessionByOwner(
    String? ownerId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionByOwner,
          [
            ownerId,
            sessionId,
          ],
        ),
        returnValue: _i4.Future<_i7.Session?>.value(),
      ) as _i4.Future<_i7.Session?>);

  @override
  _i4.Future<void> createSession(
    String? userId,
    _i7.Session? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [
            userId,
            session,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSession(
    String? userId,
    _i7.Session? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [
            userId,
            session,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSession(
    String? userId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [
            userId,
            sessionId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i7.Session>> userSessionsStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #userSessionsStream,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i7.Session>>.empty(),
      ) as _i4.Stream<List<_i7.Session>>);

  @override
  _i4.Future<List<_i7.Session>> getPresetSessions() => (super.noSuchMethod(
        Invocation.method(
          #getPresetSessions,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Session>>.value(<_i7.Session>[]),
      ) as _i4.Future<List<_i7.Session>>);

  @override
  _i4.Future<List<_i8.Program>> getPrograms() => (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Program>>.value(<_i8.Program>[]),
      ) as _i4.Future<List<_i8.Program>>);

  @override
  _i4.Future<_i8.Program?> getProgramById(
    String? programId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgramById,
          [programId],
          {#userId: userId},
        ),
        returnValue: _i4.Future<_i8.Program?>.value(),
      ) as _i4.Future<_i8.Program?>);

  @override
  _i4.Stream<_i8.Program?> subscribeToProgram(
    String? programId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToProgram,
          [programId],
          {#userId: userId},
        ),
        returnValue: _i4.Stream<_i8.Program?>.empty(),
      ) as _i4.Stream<_i8.Program?>);

  @override
  _i4.Future<List<_i8.Program>> getUserPrograms(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPrograms,
          [userId],
        ),
        returnValue: _i4.Future<List<_i8.Program>>.value(<_i8.Program>[]),
      ) as _i4.Future<List<_i8.Program>>);

  @override
  _i4.Future<void> createProgram(
    String? userId,
    _i8.Program? program,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProgram,
          [
            userId,
            program,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProgram(
    String? userId,
    _i8.Program? program,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgram,
          [
            userId,
            program,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProgram(
    String? userId,
    String? programId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProgram,
          [
            userId,
            programId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getWorkoutHistory({
    required String? userId,
    int? limit = 180,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutHistory,
          [],
          {
            #userId: userId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMonthlyExerciseAggregates({
    required String? userId,
    required String? monthKey,
    int? limit = 2000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyExerciseAggregates,
          [],
          {
            #userId: userId,
            #monthKey: monthKey,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getMonthlyWorkoutSummary({
    required String? userId,
    required String? monthKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyWorkoutSummary,
          [],
          {
            #userId: userId,
            #monthKey: monthKey,
          },
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<String> saveWorkoutHistory({
    required String? userId,
    required String? sessionId,
    required DateTime? completedAt,
    required int? duration,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkoutHistory,
          [],
          {
            #userId: userId,
            #sessionId: sessionId,
            #completedAt: completedAt,
            #duration: duration,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #saveWorkoutHistory,
            [],
            {
              #userId: userId,
              #sessionId: sessionId,
              #completedAt: completedAt,
              #duration: duration,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> getStreakData({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakData,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Set<String>> getUnlockedAchievementIds(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnlockedAchievementIds,
          [userId],
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<void> unlockAchievement({
    required String? userId,
    required String? achievementId,
    required DateTime? unlockedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlockAchievement,
          [],
          {
            #userId: userId,
            #achievementId: achievementId,
            #unlockedAt: unlockedAt,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getTotalDoneReps(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getTotalDoneReps,
          [userId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getTotalWorkoutCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getTotalWorkoutCount,
          [userId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getProgramsCompleted(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getProgramsCompleted,
          [userId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> incrementProgramsCompleted(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementProgramsCompleted,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> getChallengeCompletion({
    required String? userId,
    required String? challengeId,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChallengeCompletion,
          [],
          {
            #userId: userId,
            #challengeId: challengeId,
            #date: date,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setChallengeCompleted({
    required String? userId,
    required String? challengeId,
    required DateTime? date,
    required bool? completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setChallengeCompleted,
          [],
          {
            #userId: userId,
            #challengeId: challengeId,
            #date: date,
            #completed: completed,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i10.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i2.User?>.empty(),
      ) as _i4.Stream<_i2.User?>);

  @override
  bool get isEmailVerified => (super.noSuchMethod(
        Invocation.getter(#isEmailVerified),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i2.UserCredential> registerWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #registerWithEmailPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #signInWithEmailPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i4.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #signInWithApple,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> signInWithGitHub() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGitHub,
          [],
        ),
        returnValue: _i4.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #signInWithGitHub,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reloadUser() => (super.noSuchMethod(
        Invocation.method(
          #reloadUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
