// Mocks generated by Mockito 5.4.4 from annotations
// in workin_fit/test/unit/providers/workout_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:workin_fit/models/exercise.dart' as _i5;
import 'package:workin_fit/models/program.dart' as _i6;
import 'package:workin_fit/models/session.dart' as _i4;
import 'package:workin_fit/services/sync_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Session>> getSessions(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.Session>>.value(<_i4.Session>[]),
      ) as _i3.Future<List<_i4.Session>>);

  @override
  _i3.Future<void> createSession(
    String? userId,
    _i4.Session? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [
            userId,
            session,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSession(
    String? userId,
    _i4.Session? session,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [
            userId,
            session,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSession(
    String? userId,
    String? sessionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [
            userId,
            sessionId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> syncPendingChanges(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #syncPendingChanges,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Exercise>> getExercises(
          {void Function()? onCacheUpdated}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [],
          {#onCacheUpdated: onCacheUpdated},
        ),
        returnValue: _i3.Future<List<_i5.Exercise>>.value(<_i5.Exercise>[]),
      ) as _i3.Future<List<_i5.Exercise>>);

  @override
  _i3.Future<List<_i5.Exercise>> refreshExercises() => (super.noSuchMethod(
        Invocation.method(
          #refreshExercises,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Exercise>>.value(<_i5.Exercise>[]),
      ) as _i3.Future<List<_i5.Exercise>>);

  @override
  _i3.Future<_i5.Exercise?> getExerciseById(
    String? id, {
    void Function()? onCacheUpdated,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExerciseById,
          [id],
          {#onCacheUpdated: onCacheUpdated},
        ),
        returnValue: _i3.Future<_i5.Exercise?>.value(),
      ) as _i3.Future<_i5.Exercise?>);

  @override
  _i3.Future<List<_i5.Exercise>> searchExercises(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchExercises,
          [query],
        ),
        returnValue: _i3.Future<List<_i5.Exercise>>.value(<_i5.Exercise>[]),
      ) as _i3.Future<List<_i5.Exercise>>);

  @override
  _i3.Future<List<_i4.Session>> getPresetSessions() => (super.noSuchMethod(
        Invocation.method(
          #getPresetSessions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Session>>.value(<_i4.Session>[]),
      ) as _i3.Future<List<_i4.Session>>);

  @override
  _i3.Future<List<_i6.Program>> getPrograms({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i6.Program>>.value(<_i6.Program>[]),
      ) as _i3.Future<List<_i6.Program>>);

  @override
  _i3.Future<_i6.Program?> getProgramById(
    String? programId, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgramById,
          [programId],
          {#userId: userId},
        ),
        returnValue: _i3.Future<_i6.Program?>.value(),
      ) as _i3.Future<_i6.Program?>);

  @override
  _i3.Future<void> createProgram(
    String? userId,
    _i6.Program? program,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProgram,
          [
            userId,
            program,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateProgram(
    String? userId,
    _i6.Program? program,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgram,
          [
            userId,
            program,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProgram(
    String? userId,
    String? programId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProgram,
          [
            userId,
            programId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
